DROP TABLE TMP_REVISION_CLIENTE PURGE;

CREATE TABLE TMP_REVISION_CLIENTE AS
WITH BASE_ESC AS (
SELECT MIN(A.PERIODO) AS PERIODO_ESC, A.RUCCOMPANIA
FROM ODS_CDG.Cg_Convergente_B2b A
WHERE 1=1
  AND A.PERIODO >= '202501'
  AND A.FLAG_FUENTE IN ('ET')
  AND A.TIPO_NEGOCIO = 'NEGOCIO MOVIL'
  AND A.CGE_AGRUPA_2 = 'CARGO BASICO NETO'
GROUP BY A.RUCCOMPANIA
),
BASE AS (
SELECT 
  A.PERIODO, 
  DECODE(A.FLAG_FUENTE,'RECLA - TDE','ET',A.FLAG_FUENTE) AS FLAG_FUENTE,
  A.TIPO_NEGOCIO, A.CGE_AGRUPA_2, A.TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  NVL(A.RUCCOMPANIA,B.CSCOMPTAXNO) RUCCOMPANIA,
  SUM(A.MONTOFACTURADO) MONTOFACTURADO 
FROM ODS_CDG.Cg_Convergente_B2b A
  LEFT JOIN CUSTOMER_ALL@PBSCS_LM.WORLD B
      ON B.CUSTCODE = DECODE(NUMEROCUENTARESPONSABLE,'4.9596.210000000000','4.9596.21',NUMEROCUENTARESPONSABLE)
WHERE 1=1
  AND A.PERIODO >= '202501'
  AND A.FLAG_FUENTE IN ('L','ET','RECLA - TDE')
  AND A.TIPO_NEGOCIO = 'NEGOCIO MOVIL'
  AND A.CGE_AGRUPA_2 = 'CARGO BASICO NETO'
GROUP BY 
  A.PERIODO, 
  DECODE(A.FLAG_FUENTE,'RECLA - TDE','ET',A.FLAG_FUENTE),
  A.TIPO_NEGOCIO, A.CGE_AGRUPA_2, A.TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  NVL(A.RUCCOMPANIA,B.CSCOMPTAXNO)
UNION ALL
SELECT 
  A.PERIODO, 
  'O' AS FLAG_FUENTE,
  'NEGOCIO MOVIL' AS TIPO_NEGOCIO, 'CARGO BASICO NETO' AS CGE_AGRUPA_2, REGEXP_SUBSTR(A.GLOSAS, '[^|]+',1,3) AS TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA,
  SUM(A.MONTOFACTURADO) MONTOFACTURADO 
FROM CGE_RS_FEES_HIST A
WHERE 1=1
  AND A.PERIODO >= '202501'
  AND A.TECNO_MIX IN ('VOZ','BAM')
  --AND A.TIPO_NEGOCIO = 'NEGOCIO MOVIL'
  AND REGEXP_SUBSTR(A.GLOSAS, '[^|]+',1,3) IN ('CARGO BASICO','DESCUENTOS - NC')
  AND NVL(COD_PROMO,'-') NOT IN ('1E2095')
GROUP BY 
  A.PERIODO, 
  REGEXP_SUBSTR(A.GLOSAS, '[^|]+',1,3), 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA
UNION ALL
SELECT 
  NVL(TO_CHAR(A.FECHA_RECIBO_REFERENCIA,'YYYYMM'),A.PERIODO) AS PERIODO, 
  'LEG - ' || A.TIPO_DOCUMENTO_REC AS FLAG_FUENTE,
  'NEGOCIO MOVIL' AS TIPO_NEGOCIO, 'CARGO BASICO NETO' AS CGE_AGRUPA_2, 'CARGO BASICO' AS TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.DOCUMENTO2 AS RUCCOMPANIA,
  SUM(A.MONTO_VV18) MONTOFACTURADO 
FROM HIST_SERIES_LEG A
WHERE 1=1
  AND NVL(TO_CHAR(A.FECHA_RECIBO_REFERENCIA,'YYYYMM'),A.PERIODO) >= '202501'
  AND A.SERIE <> 'F005'
  AND A.TMCODE IN ('39','',NULL)
GROUP BY 
  NVL(TO_CHAR(A.FECHA_RECIBO_REFERENCIA,'YYYYMM'),A.PERIODO), 
  'LEG - ' || A.TIPO_DOCUMENTO_REC,
  --'NEGOCIO MOVIL' AS TIPO_NEGOCIO, 'CARGO BASICO NETO' AS CGE_AGRUPA_2, 'CARGO BASICO' AS TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.DOCUMENTO2
UNION ALL
SELECT 
  NVL(TO_CHAR(A.FECHA_REF,'YYYYMM'),A.PERIODO) AS PERIODO, 
  'TDE - NOTA CREDITO' AS FLAG_FUENTE,
  F.CORTEPL2 AS TIPO_NEGOCIO, F.CORTEPL4 AS CGE_AGRUPA_2, F.CORTEPL5 AS TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA,
  SUM(A.MONTO_ITEM_SIN_IGV) MONTOFACTURADO 
FROM CGE_FACTURACION_B2B_TDE A
  LEFT JOIN CGE_CONCEPTO_FACTURACION F
    ON A.CONCEPTO_FACTURACION = F.CONCEPTO
WHERE 1=1
  AND NVL(TO_CHAR(A.FECHA_REF,'YYYYMM'),A.PERIODO) >= '202501'
  AND UPPER(A.TIPO_DOCUMENTO) <> 'RECIBO VENTA'
  AND F.CORTEPL4 = 'CARGO BASICO NETO'
GROUP BY 
  NVL(TO_CHAR(A.FECHA_REF,'YYYYMM'),A.PERIODO), 
  F.CORTEPL2, F.CORTEPL4, F.CORTEPL5, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA
UNION ALL
SELECT 
  A.PERIODO, 
  'ET' AS FLAG_FUENTE,
  F.CORTEPL2 AS TIPO_NEGOCIO, F.CORTEPL4 AS CGE_AGRUPA_2, F.CORTEPL5 AS TIPO_SERVICIO, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA,
  SUM(A.montoservicioscontratadosnew) MONTOFACTURADO 
FROM TMP_CGE_INGCONVERGENTE_V2 A
  LEFT JOIN CGE_CONCEPTO_FACTURACION F
    ON A.CORTEPL30 = F.CONCEPTO
WHERE 1=1
  AND A.PERIODO >= '202501'
  AND FUENTE = 'TDE - B2B - RECIBO - FACT'
  AND F.CORTEPL4 = 'CARGO BASICO NETO'
GROUP BY 
  A.PERIODO, 
  F.CORTEPL2, F.CORTEPL4, F.CORTEPL5, 
  --SUBSTR(A.CODIGOGLOSA,1,35) CODIGOGLOSA, 
  A.RUCCOMPANIA
),
BASE2 AS (
SELECT 
  A.PERIODO, 
  A.FLAG_FUENTE,
  CASE
    WHEN A.FLAG_FUENTE IN ('L','O') THEN 'FUENTE LEGADOS'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'FUENTE LEGADOS'
    ELSE 'FUENTE ESC'
  END FUENTE_1,
  CASE
    WHEN A.FLAG_FUENTE = 'L' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'O' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DEBITO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DE DEBITO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'CARGO BASICO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'DESCUENTOS - NC' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE LIKE 'TDE - %' THEN 'DESCUENTOS'
  END FUENTE_2,
  CASE
    WHEN A.FLAG_FUENTE = 'L' THEN 'RECIBO'
    WHEN A.FLAG_FUENTE = 'O' THEN 'OCC'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DEBITO' THEN 'ND'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DE DEBITO' THEN 'ND'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'NC'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'CARGO BASICO' THEN 'RECIBO'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'DESCUENTOS - NC' THEN 'OCC'
    WHEN A.FLAG_FUENTE LIKE 'TDE - %' THEN 'NC'
  END FUENTE_3,
  A.TIPO_NEGOCIO, 
  A.CGE_AGRUPA_2, 
  --A.TIPO_SERVICIO, 
  --A.CODIGOGLOSA, 
  D.CICLO, 
  A.RUCCOMPANIA, 
  C.RAZONSOCIAL, 
  A.RUCCOMPANIA||' - '||C.RAZONSOCIAL AS RUC_RZ, 
  E.NEW_SEGMENTO_2021, 
  E.NEW_SUBSEGMENTO_2021, 
  E.GOBIERNO, 
  G.RS_CARTERA_CANAL_N1,
  G.RS_CARTERA_CANAL_N2,
  G.RS_CARTERA_CANAL_N3,
  G.RS_CARTERA_CANAL_N4,
  G.RS_CARTERA_CANAL_N5,
  B.PERIODO_ESC, 
  --CASE WHEN F.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END AS FLG_PRUEBA,
  CASE WHEN UPPER(C.RAZONSOCIAL) LIKE '%PRUEBA%' THEN 'SI' ELSE 'NO' END AS FLG_PRUEBA,
  CASE WHEN A.RUCCOMPANIA = '20106897914' THEN 'SI' ELSE 'NO' END AS FLG_ENTEL,
  SUM(DECODE(A.TIPO_SERVICIO,'CARGO BASICO',A.MONTOFACTURADO,0)) MONTO_CB,
  SUM(DECODE(A.TIPO_SERVICIO,'DESCUENTOS - NC',A.MONTOFACTURADO,0)) MONTO_DSCT
FROM BASE A
  LEFT JOIN BASE_ESC B
    ON A.RUCCOMPANIA = B.RUCCOMPANIA
  LEFT JOIN V_MAESTRO_RZ_EXPORT C
    ON A.RUCCOMPANIA = C.RUCCOMPANIA
  LEFT JOIN MAESTRO_CICLOS_FINAL D
    ON A.RUCCOMPANIA = D.RUCCOMPANIA
  LEFT JOIN (SELECT * FROM seg_202505 WHERE PERIODO = '202601') E
    ON A.RUCCOMPANIA = E.RUC_DNI --AND A.PERIODO = E.PERIODO
  --LEFT JOIN v_rucs_prueba F
  --  ON A.RUCCOMPANIA = F.RUCCOMPANIA
  LEFT JOIN (SELECT * FROM CGE_TBCARTERA_CIERRE WHERE PERIODO = '202601') G
    ON A.RUCCOMPANIA = G.RUCCOMPANIA --AND A.PERIODO = G.PERIODO
GROUP BY
  A.PERIODO, 
  A.FLAG_FUENTE,
  CASE
    WHEN A.FLAG_FUENTE IN ('L','O') THEN 'FUENTE LEGADOS'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'FUENTE LEGADOS'
    ELSE 'FUENTE ESC'
  END ,
  CASE
    WHEN A.FLAG_FUENTE = 'L' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'O' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DEBITO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DE DEBITO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'CARGO BASICO' THEN 'CARGO BASICO'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'DESCUENTOS - NC' THEN 'DESCUENTOS'
    WHEN A.FLAG_FUENTE LIKE 'TDE - %' THEN 'DESCUENTOS'
  END ,
  CASE
    WHEN A.FLAG_FUENTE = 'L' THEN 'RECIBO'
    WHEN A.FLAG_FUENTE = 'O' THEN 'OCC'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DEBITO' THEN 'ND'
    WHEN A.FLAG_FUENTE = 'LEG - NOTA DE DEBITO' THEN 'ND'
    WHEN A.FLAG_FUENTE LIKE 'LEG -%' THEN 'NC'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'CARGO BASICO' THEN 'RECIBO'
    WHEN A.FLAG_FUENTE = 'ET' AND A.TIPO_SERVICIO = 'DESCUENTOS - NC' THEN 'OCC'
    WHEN A.FLAG_FUENTE LIKE 'TDE - %' THEN 'NC'
  END,
  A.TIPO_NEGOCIO, 
  A.CGE_AGRUPA_2, 
  --A.TIPO_SERVICIO, 
  --A.CODIGOGLOSA, 
  D.CICLO, 
  A.RUCCOMPANIA, 
  C.RAZONSOCIAL, 
  A.RUCCOMPANIA||' - '||C.RAZONSOCIAL, 
  E.NEW_SEGMENTO_2021, 
  E.NEW_SUBSEGMENTO_2021, 
  E.GOBIERNO, 
  G.RS_CARTERA_CANAL_N1,
  G.RS_CARTERA_CANAL_N2,
  G.RS_CARTERA_CANAL_N3,
  G.RS_CARTERA_CANAL_N4,
  G.RS_CARTERA_CANAL_N5,
  B.PERIODO_ESC, 
  CASE WHEN UPPER(C.RAZONSOCIAL) LIKE '%PRUEBA%' THEN 'SI' ELSE 'NO' END,
  CASE WHEN A.RUCCOMPANIA = '20106897914' THEN 'SI' ELSE 'NO' END
)
SELECT 
  A.*,
  A.MONTO_CB + A.MONTO_DSCT AS RENTA
FROM BASE2 A
;
----------------------------------------------------------------------------------

DROP TABLE RECIBOS_CLIENTE_B2B PURGE;

CREATE TABLE RECIBOS_CLIENTE_B2B AS
WITH BASE_VAR_RATIO_A AS (
SELECT
  PERIODO,
  RUCCOMPANIA,
  SUM(MONTO_CB) AS MONTO_CB,
  SUM(MONTO_DSCT) AS MONTO_DSCT
FROM TMP_REVISION_CLIENTE
GROUP BY
  PERIODO,
  RUCCOMPANIA
),
BASE_VAR_RATIO_B AS (
SELECT DISTINCT
  PERIODO,
  RUCCOMPANIA,
  ROUND(ABS(NVL(MONTO_DSCT / NULLIF(MONTO_CB,0),0)),2) AS RATIO
FROM BASE_VAR_RATIO_A
),
BASE_VAR_RATIO_C AS (
SELECT 
  RUCCOMPANIA,
  SUM(DECODE(PERIODO,'202508',RATIO,0)) AS RATIO_202508,
  SUM(DECODE(PERIODO,'202509',RATIO,0)) AS RATIO_202509,
  SUM(DECODE(PERIODO,'202510',RATIO,0)) AS RATIO_202510,
  SUM(DECODE(PERIODO,'202511',RATIO,0)) AS RATIO_202511,
  SUM(DECODE(PERIODO,'202512',RATIO,0)) AS RATIO_202512,
  SUM(DECODE(PERIODO,'202601',RATIO,0)) AS RATIO_202601
FROM BASE_VAR_RATIO_B
GROUP BY 
  RUCCOMPANIA
),
BASE_VAR_RATIO_D AS (
SELECT
  RUCCOMPANIA,
  ABS(RATIO_202601 - RATIO_202512) AS MOM_RATIO_202601,
  ABS(RATIO_202512 - RATIO_202511) AS MOM_RATIO_202512,
  ABS(RATIO_202511 - RATIO_202510) AS MOM_RATIO_202511,
  ABS(RATIO_202510 - RATIO_202509) AS MOM_RATIO_202510
FROM BASE_VAR_RATIO_C
),
BASE_VAR_RATIO_E AS (
SELECT
  RUCCOMPANIA,
  GREATEST(MOM_RATIO_202601, MOM_RATIO_202512, MOM_RATIO_202511, MOM_RATIO_202510) AS MOM_RATIO_MAX
FROM BASE_VAR_RATIO_D
),
BASE_VAR_RATIO_F AS (
SELECT
  RUCCOMPANIA,
  --MOM_RATIO_MAX,
  CASE
    WHEN MOM_RATIO_MAX < 0 THEN 'MENOR A 0%'
    WHEN MOM_RATIO_MAX = 0 THEN '0%'
    WHEN MOM_RATIO_MAX > 0 AND MOM_RATIO_MAX <= 0.1 THEN '0% - 10%' 
    WHEN MOM_RATIO_MAX > 0.1 AND MOM_RATIO_MAX <= 0.2 THEN '10% - 20%' 
    WHEN MOM_RATIO_MAX > 0.2 AND MOM_RATIO_MAX <= 0.3 THEN '20% - 30%' 
    WHEN MOM_RATIO_MAX > 0.3 AND MOM_RATIO_MAX <= 0.4 THEN '30% - 40%' 
    WHEN MOM_RATIO_MAX > 0.4 AND MOM_RATIO_MAX <= 0.5 THEN '40% - 50%' 
    WHEN MOM_RATIO_MAX > 0.5 AND MOM_RATIO_MAX <= 0.6 THEN '50% - 60%' 
    WHEN MOM_RATIO_MAX > 0.6 AND MOM_RATIO_MAX <= 0.7 THEN '60% - 70%' 
    WHEN MOM_RATIO_MAX > 0.7 AND MOM_RATIO_MAX <= 0.8 THEN '70% - 80%' 
    WHEN MOM_RATIO_MAX > 0.8 AND MOM_RATIO_MAX <= 0.9 THEN '80% - 90%' 
    WHEN MOM_RATIO_MAX > 0.9 AND MOM_RATIO_MAX <= 1 THEN '90% - 100%' 
    ELSE 'MAYOR A 100%' 
  END RANGO_RATIO_MAX
FROM BASE_VAR_RATIO_E
),
ANALISIS_A AS (
SELECT 
  A.PERIODO, 
  A.FLAG_FUENTE, 
  A.FUENTE_1, A.FUENTE_2, A.FUENTE_3,
  A.TIPO_NEGOCIO, A.CGE_AGRUPA_2, 
  A.CICLO, 
  A.RUCCOMPANIA, A.RAZONSOCIAL, A.RUC_RZ, 
  A.NEW_SEGMENTO_2021, A.NEW_SUBSEGMENTO_2021, A.GOBIERNO, 
  A.RS_CARTERA_CANAL_N1, A.RS_CARTERA_CANAL_N2, A.RS_CARTERA_CANAL_N3, A.RS_CARTERA_CANAL_N4, A.RS_CARTERA_CANAL_N5, 
  A.PERIODO_ESC, 
  A.FLG_PRUEBA, A.FLG_ENTEL, 
  CASE WHEN B.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END AS FLG_DESACT_202511,
  CASE WHEN C.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END AS FLG_SUSPEN_202511,
  CASE WHEN D.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END AS FLG_NUEVO_ESC,
  SUM(A.MONTO_CB) MONTO_CB, SUM(A.MONTO_DSCT) MONTO_DSCT, SUM(A.RENTA) RENTA
FROM TMP_REVISION_CLIENTE A
  LEFT JOIN (SELECT DISTINCT PERIODO, NUMERO_DOCUMENTO AS RUCCOMPANIA, UPPER(ESTADO_SUSCRIPTOR) ESTADO_SUSCRIPTOR 
            FROM BASE_SUCRIPTORES WHERE PERIODO = '202511' AND UPPER(ESTADO_SUSCRIPTOR) = 'DESACTIVADO') B
    ON A.RUCCOMPANIA = TO_CHAR(B.RUCCOMPANIA)
  LEFT JOIN (SELECT DISTINCT PERIODO, NUMERO_DOCUMENTO AS RUCCOMPANIA, UPPER(ESTADO_SUSCRIPTOR) ESTADO_SUSCRIPTOR 
            FROM BASE_SUCRIPTORES WHERE PERIODO = '202511' AND UPPER(ESTADO_SUSCRIPTOR) LIKE 'SUSPENDIDO%') C
    ON A.RUCCOMPANIA = TO_CHAR(C.RUCCOMPANIA)
  LEFT JOIN (SELECT DISTINCT RUCCOMPANIA FROM TMP_REVISION_CLIENTE WHERE PERIODO = PERIODO_ESC) D
    ON A.RUCCOMPANIA = D.RUCCOMPANIA
GROUP BY
  A.PERIODO, 
  A.FLAG_FUENTE,
  A.FUENTE_1, A.FUENTE_2, A.FUENTE_3,
  A.TIPO_NEGOCIO, A.CGE_AGRUPA_2, 
  A.CICLO, 
  A.RUCCOMPANIA, A.RAZONSOCIAL, A.RUC_RZ, 
  A.NEW_SEGMENTO_2021, A.NEW_SUBSEGMENTO_2021, A.GOBIERNO, 
  A.RS_CARTERA_CANAL_N1, A.RS_CARTERA_CANAL_N2, A.RS_CARTERA_CANAL_N3, A.RS_CARTERA_CANAL_N4, A.RS_CARTERA_CANAL_N5, 
  A.PERIODO_ESC, 
  A.FLG_PRUEBA, A.FLG_ENTEL,
  CASE WHEN B.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END,
  CASE WHEN C.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END,
  CASE WHEN D.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END
),
ANALISIS_B AS (
SELECT
  --PERIODO, 
  FUENTE_1, FUENTE_2, FUENTE_3,
  CICLO, 
  RUCCOMPANIA, RAZONSOCIAL, RUC_RZ, 
  NEW_SEGMENTO_2021, NEW_SUBSEGMENTO_2021, GOBIERNO, 
  RS_CARTERA_CANAL_N1, RS_CARTERA_CANAL_N2, RS_CARTERA_CANAL_N3, RS_CARTERA_CANAL_N4, RS_CARTERA_CANAL_N5, 
  PERIODO_ESC, 
  FLG_PRUEBA, FLG_ENTEL, 
  FLG_DESACT_202511, FLG_SUSPEN_202511, 
  FLG_NUEVO_ESC,
  SUM(DECODE(PERIODO,'202501',RENTA,0)) R_202501,
  SUM(DECODE(PERIODO,'202502',RENTA,0)) R_202502,
  SUM(DECODE(PERIODO,'202503',RENTA,0)) R_202503,
  SUM(DECODE(PERIODO,'202504',RENTA,0)) R_202504,
  SUM(DECODE(PERIODO,'202505',RENTA,0)) R_202505,
  SUM(DECODE(PERIODO,'202506',RENTA,0)) R_202506,
  SUM(DECODE(PERIODO,'202507',RENTA,0)) R_202507,
  SUM(DECODE(PERIODO,'202508',RENTA,0)) R_202508,
  SUM(DECODE(PERIODO,'202509',RENTA,0)) R_202509,
  SUM(DECODE(PERIODO,'202510',RENTA,0)) R_202510,
  SUM(DECODE(PERIODO,'202511',RENTA,0)) R_202511,
  SUM(DECODE(PERIODO,'202512',RENTA,0)) R_202512,
  SUM(DECODE(PERIODO,'202601',RENTA,0)) R_202601
FROM ANALISIS_A
GROUP BY
  --PERIODO, 
  FUENTE_1, FUENTE_2, FUENTE_3,
  CICLO, 
  RUCCOMPANIA, RAZONSOCIAL, RUC_RZ, 
  NEW_SEGMENTO_2021, NEW_SUBSEGMENTO_2021, GOBIERNO, 
  RS_CARTERA_CANAL_N1, RS_CARTERA_CANAL_N2, RS_CARTERA_CANAL_N3, RS_CARTERA_CANAL_N4, RS_CARTERA_CANAL_N5, 
  PERIODO_ESC, 
  FLG_PRUEBA, FLG_ENTEL, 
  FLG_DESACT_202511, FLG_SUSPEN_202511, 
  FLG_NUEVO_ESC
),
ANALISIS_C AS (
SELECT
  A.*,
  R_202501 + R_202502 + R_202503 + R_202504 + R_202505 + R_202506 + R_202507 + R_202508 + R_202509 + R_202510 + R_202511 + R_202512 AS R_2025,
  --R_202601 + R_202602 + R_202603 + R_202604 + R_202605 + R_202606 + R_202607 + R_202608 + R_202609 + R_202610 + R_202611 + R_202612 AS R_2026,
  CASE WHEN B.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END RENTA_202512,
  CASE WHEN C.RUCCOMPANIA IS NOT NULL THEN 'SI' ELSE 'NO' END RENTA_202601,
  R_202601 - R_202512 AS VAR_202601,
  D.RANGO_RATIO_MAX
FROM ANALISIS_B A
  LEFT JOIN (SELECT DISTINCT RUCCOMPANIA FROM ANALISIS_A WHERE PERIODO = '202512' AND RENTA <> 0) B
    ON A.RUCCOMPANIA = B.RUCCOMPANIA
  LEFT JOIN (SELECT DISTINCT RUCCOMPANIA FROM ANALISIS_A WHERE PERIODO = '202601' AND RENTA <> 0) C
    ON A.RUCCOMPANIA = C.RUCCOMPANIA
  LEFT JOIN BASE_VAR_RATIO_F D
    ON A.RUCCOMPANIA = D.RUCCOMPANIA 
)
SELECT * FROM ANALISIS_C
--WHERE RUCCOMPANIA = '20551706495'
;

SELECT 
  RUCCOMPANIA,
  SUM(R_202501) R_202501,
  SUM(R_202502) R_202502,
  SUM(R_202503) R_202503,
  SUM(R_202504) R_202504,
  SUM(R_202505) R_202505,
  SUM(R_202506) R_202506,
  SUM(R_202507) R_202507,
  SUM(R_202508) R_202508,
  SUM(R_202509) R_202509,
  SUM(R_202510) R_202510,
  SUM(R_202511) R_202511,
  SUM(R_202512) R_202512,
  SUM(R_202601) R_202601
FROM RECIBOS_CLIENTE_B2B
WHERE RUCCOMPANIA = '20505712111'
GROUP BY RUCCOMPANIA;

SELECT * FROM RECIBOS_CLIENTE_B2B;