
--CREANDO TABLA TEMPORAL DEL MES A ACTUALIZAR
DROP TABLE CGE_RS_TDE_V1 PURGE;

CREATE TABLE CGE_RS_TDE_V1 AS
SELECT 
    PERIODO,
    CODIGOCONCEPTO, 
    CODIGOGLOSA,
    DECODE(NUMEROCUENTARESPONSABLE,'4.9596.210000000000','4.9596.21',NUMEROCUENTARESPONSABLE) NUMEROCUENTARESPONSABLE, 
    TIPODCUENTA, 
    CICLO, 
    MONTOFACTURADO,
    RUCCOMPANIA, NEW_SEGMENTO_2021, NEW_SUBSEGMENTO_2021,
    TECNOLOGIA_PANEL TECNO_GDI, VISTA_IDG, VISTA_IDG0, VISTA_IDG1,
    TIPO_INGRESO CORTEPL1, TIPO_NEGOCIO CORTEPL2, CGE_AGRUPA_1 CORTEPL3, CGE_AGRUPA_2 CORTEPL4, TIPO_SERVICIO CORTEPL5
  FROM ODS_CDG.Cg_Convergente_B2b
  
  WHERE PERIODO = '&PERIODO'
    AND FLAG_FUENTE = 'ET'
  ; 
  
--VALIDACION
--POR MONTO
SELECT 'ODS_CDG.Cg_Convergente_B2b' TABLA, SUM(MONTOFACTURADO) MONTO FROM ODS_CDG.Cg_Convergente_B2b WHERE PERIODO = '&PERIODO' AND FLAG_FUENTE = 'ET'
UNION ALL
SELECT 'CGE_RS_TDE_V1' TABLA, SUM(MONTOFACTURADO) MONTO FROM CGE_RS_TDE_V1
;
--RUC VACIOS
SELECT * FROM CGE_RS_TDE_V1 WHERE TRIM(RUCCOMPANIA) IS NULL ORDER BY 1;


--PARA EL BI
DELETE FROM ODS_CGE.TMP_CGE_INGCONVERGENTE_V2
WHERE PERIODO = '&PERIODO' AND FUENTE = 'TDE - B2B - RECIBO'; 
COMMIT;
  
INSERT INTO ODS_CGE.TMP_CGE_INGCONVERGENTE_V2
  SELECT
    *
  FROM V_RS_CGE_TDE_V1
  WHERE PERIODO = '&PERIODO';
COMMIT;


--VALIDACION
--POR MONTO
SELECT 'ODS_CDG.Cg_Convergente_B2b' TABLA, PERIODO, SUM(MONTOFACTURADO) MONTO FROM ODS_CDG.Cg_Convergente_B2b WHERE PERIODO >= '&PERIODO' AND FLAG_FUENTE = 'ET'
GROUP BY PERIODO
UNION ALL
SELECT 'CGE_RS_TDE_V1' TABLA, PERIODO, SUM(MONTOFACTURADO) MONTO FROM CGE_RS_TDE_V1 WHERE PERIODO >= '&PERIODO'
GROUP BY PERIODO
UNION ALL
SELECT 'TMP_CGE_INGCONVERGENTE_V2' TABLA,PERIODO, SUM(montoservicioscontratadosnew ) MONTO FROM TMP_CGE_INGCONVERGENTE_V2 WHERE PERIODO >= '&PERIODO' AND FUENTE = 'TDE - B2B - RECIBO'
GROUP BY PERIODO
;


